language: c
sudo: false

matrix:
  include:

    #==============================
    #
    #          osx gcc
    #
    #==============================

    - os: osx
      osx_image: xcode10.1
      compiler: gcc-4.9
      env: MATRIX_EVAL="brew install gcc@4.9 && CC=gcc-4.9"

    - os: osx
      osx_image: xcode10.1
      compiler: gcc-5
      env: MATRIX_EVAL="brew install gcc@5 && CC=gcc-5"

    - os: osx
      osx_image: xcode10.2
      compiler: gcc-6
      env: MATRIX_EVAL="brew install gcc@6 && CC=gcc-6"

    - os: osx
      osx_image: xcode10.2
      compiler: gcc-7
      env: MATRIX_EVAL="brew install gcc@7 && CC=gcc-7"

    - os: osx
      osx_image: xcode10.2
      compiler: gcc-8
      env: MATRIX_EVAL="CC=gcc-8"

    #==============================
    #
    #          osx clang
    #
    #==============================

    - os: osx
      osx_image: xcode6.4
      env: MATRIX_EVAL="CC=clang"

    - os: osx
      osx_image: xcode7.3
      env: MATRIX_EVAL="CC=clang"

    - os: osx
      osx_image: xcode8
      env: MATRIX_EVAL="CC=clang"

    - os: osx
      osx_image: xcode8.3
      env: MATRIX_EVAL="CC=clang"

    - os: osx
      osx_image: xcode9.2
      env: MATRIX_EVAL="CC=clang"

    - os: osx
      osx_image: xcode9.4
      env: MATRIX_EVAL="CC=clang"

    - os: osx
      osx_image: xcode10.1
      env: MATRIX_EVAL="CC=clang"

    - os: osx
      osx_image: xcode10.2
      env: MATRIX_EVAL="CC=clang"

    #==============================
    #
    #          linux gcc 
    #
    #==============================
    
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env: MATRIX_EVAL="CC=gcc-4.9"

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: MATRIX_EVAL="CC=gcc-5"

    - os: linux
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: MATRIX_EVAL="CC=gcc-6"

    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env: MATRIX_EVAL="CC=gcc-7"

    - os: linux
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env: MATRIX_EVAL="CC=gcc-8"

    #==============================
    #
    #          linux clang 
    #
    #==============================

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0"

before_install:
  - eval ${MATRIX_EVAL}

script:
  - make all
  - make clean
