language: c
sudo: false

matrix:
  include:
    #==============================
    #
    #          osx gcc 
    #
    #==============================

    - os: osx
      osx_image: xcode6.4
      compiler: gcc

    - os: osx
      osx_image: xcode7.3
      compiler: gcc

    - os: osx
      osx_image: xcode8
      compiler: gcc

    - os: osx
      osx_image: xcode8.3
      compiler: gcc

    - os: osx
      osx_image: xcode9
      compiler: gcc

    - os: osx
      osx_image: xcode9.1
      compiler: gcc

    - os: osx
      osx_image: xcode9.2
      compiler: gcc

    - os: osx
      osx_image: xcode9.3
      compiler: gcc

    - os: osx
      osx_image: xcode9.4
      compiler: gcc

    - os: osx
      osx_image: xcode10
      compiler: gcc

    #==============================
    #
    #          linux gcc
    #
    #==============================
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      compiler: gcc

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      compiler: gcc

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      compiler: gcc

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: gcc

before_install:
  - eval

script:
  - make all
  - make clean
